---
- hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi
  tasks:

    - name: installation du produit XH2 a partir du SAVF
      ibmi_install_product_from_savf:
        product: 5770XH2
        savf_name: 'XH2'
        savf_library: 'ANSIBLE'
      register: install_result
    - debug:
        var: install_result
