---
- hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi

  tasks:
    
    - name: creation d'un profil utilisateur TEAMxx
      ibmi_user_and_group:
        operation: 'create'
        user: 'TEAMxx'
        user_class: '*SECOFR'
      register: create_result
    - debug:
       var: create_result

    - name: affichage du profil utilisateur TEAMxx
      ibmi_user_and_group:
        operation: 'display'
        user: 'TEAMxx'
      register: display_result
    - debug:
       var: display_result
