---
- hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi

  tasks:

    - name: copie du SAVF XH2 dans la bibliotheque ANSIBLE
      ibmi_copy:
        src: '/home/files/XH2.SAVF'
        lib_name: 'ANSIBLE'
        force: True
      register: copy
    - debug:
       var: copy
