---
- hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi

  tasks:
    
    - name: execution d'une requete SQL SELECT sans variable
      ibmi_sql_query :  
        sql : 'xxxx'
      register: sql_result

    - debug:
       msg: 
       - "resultat : {{ sql_result.row }}" 
