---
- hosts: ibmi
  gather_facts: false
  collections:
    - ibm.power_ibmi

  tasks:
    
    - name: creation de la bibliotheque ANSIBLE
      ibmi_cl_command:
        cmd: crtlib lib(xxxxxxx)
        joblog: false
      register: crtlib_result
    - debug:
       var: crtlib_result
