---
- hosts: ibmi
  gather_facts: false
  collections:
     - ibm.power_ibmi
  tasks:

    - name: arret du serveur HTTP
      ibmi_tcp_server_service:
         name_list: ['*HTTP']
         state: 'stopped'
         joblog: true
      register: stop_result
    - debug:
       var: stop_result

    - name: suppression de la bibliotheque ANSIBLE
      ibmi_cl_command:
        cmd: dltlib lib(ansible)
        joblog: false
      register: dltlib_result
    - debug:
       var: dltlib_result

    - name: suppression du profil TEAMxx
      ibmi_user_and_group:
        operation: 'delete'
        user: 'TEAMxx'
      register: user_result
    - debug:
       var: user_result
     
    - name: desinstallation du produit XH2 (IBM i Access for Web)
      ibmi_uninstall_product:
        product: 5770XH2
      register: uninstall
    - debug:
       var: uninstall
